api:
  medicine:
    service-key: "5b0016030bacdf44ef216c32ac7961609fb29b0513dd411049f655aa5a2a63a0"
    url: "http://apis.data.go.kr/1471000/MdcinGrnIdntfcInfoService01/getMdcinGrnIdntfcInfoList01"

spring:
  application:
    name: YakSok

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yaksok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "@25Dldh25"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    jackson:
      serialization:
        fail-on-empty-beans: false